import dynamic from "next/dynamic";

// import NavBar from "./Components/NavBar";
// import NavInfo from "./Components/TopNav-info";
import "./globals.css";
import { Inter } from "next/font/google";

let NavInfo = dynamic(() => import("./Components/TopNav-info"));
let NavBar = dynamic(() => import("./Components/NavBar"), { ssr: false });
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <head >
      <link
            href="https://fonts.googleapis.com/css2?family=Barlow:wght@600;700&family=Ubuntu:wght@400;500&display=swap"
            rel="stylesheet"
          />
      </head>
      <body className={inter.className}>
        <div className=" bg-gray-100  shadow ">
          <NavInfo />
        </div>
        <NavBar />

        {children}
      </body>
    </html>
  );
}
