import NavBar from "./Components/NavBar";
import NavInfo from "./Components/TopNav-info";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" bg-gray-100  shadow "> <NavInfo /></div>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
